# GeoNetwork
#
# Access via "http://localhost:8080/geonetwork" (or "http://$(docker-machine ip):8080/geonetwork" if using docker-machine)
#
# Default user: admin
# Default password: admin

version: '3.6'
services:

  aogeo-geonetwork:
    image: geonetwork
    container_name: aogeo-geonetwork
    restart: always
    ports:
      - 8080:8080
    environment:
      DATA_DIR: /var/lib/jamstec-aogeo
    volumes:
      - geonetwork:/var/lib/jamstec-aogeo

volumes:
  geonetwork:
    external: true