# GeoNetwork
#
# Access via "http://localhost:8080/geonetwork" (or "http://$(docker-machine ip):8080/geonetwork" if using docker-machine)
#
# Default user: admin
# Default password: admin

version: '3.6'
services:

  postgis:
    container_name: postgis
    image: mdillon/postgis:11-alpine
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/pg_password.txt
    volumes:
      - 'aogeo-pgdata:/var/lib/postgresql/data/'
      - './secrets/pg_password.txt:/run/secrets/pg_password.txt'

  geonetwork-postgres:
    image: aogeo/geonetwork-postgres:latest
    build: ./geonetwork

  aogeo-geonetwork:
    container_name: aogeo-geonetwork
    image: aogeo/geonetwork-postgres:latest
    depends_on:
      - postgis
#    restart: on-failure
    ports:
      - 8080:8080
    environment:
      CONNECTOR_PROXYNAME: 'localhost'
      CONNECTOR_PROXYPORT: '8080'
      CONNECTOR_PROXYSCHEME: 'http'
      CONNECTOR_PROXYSECURE: 'true'
      CONNECTOR_TRUSTED_PROXIES: '172\.31\.\d{1,3}\.\d{1,3}|192\.168\.\d{1,3}\.\d{1,3}|127.0.0.1'
      CORS_ALLOWED_ORIGINS: '*'   # So other applications can harvest metadata.
      CORS_ALLOWED_METHODS: 'GET,POST,HEAD,OPTIONS,PUT'
      CORS_ALLOWED_HEADERS: 'Authorization,Origin,Accept,X-Requested-With,Content-Type,Access-Control-Request-Method,Access-Control-Request-Headers'
      CORS_SUPPORT_CREDENTIALS: 'false'
      DATA_DIR: /var/lib/geonetwork
      POSTGRES_DB_HOST: postgis
      POSTGRES_DB_USERNAME: postgres
      POSTGRES_DB_PASSWORD_FILE: /run/secrets/pg_password.txt
      TOMCAT_USER_ID: 0    # Run as root on windows or mac.  Real UID is ok on linux
      TOMCAT_GROUP_ID: 50  # Group as staff on windows or mac.  Real GID is ok on linux
    volumes:
      - type: bind
        source: './volumes/aogeo-geonetwork'
        target: '/var/lib/geonetwork'
      - './secrets/pg_password.txt:/run/secrets/pg_password.txt'

volumes:
  aogeo-pgdata:
    external: true
